apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uxwhp90fl-nodejs 
  janus-idp.io/tekton: uxwhp90fl-nodejs
  backstage.io/kubernetes-id: uxwhp90fl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uxwhp90fl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml