apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uxwhp90fl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uxwhp90fl-nodejs 
  name: uxwhp90fl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uxwhp90fl-nodejs 
